project: #项目信息
 name: framework-shell-demo
 version: @project.parent.version@
 artifactId: @project.artifactId@
 groupId: @project.groupId@
 server: 
   logserver: http://lab.towngasvcc.cn:8888/vcc/vcc-tools-log.git
   nexus: http://vccnexus.towngasvcc.com:8081
   
#server:
#  remote: true
  
spring: #应用配置
  application:
    name: ${project.name} 
  data:
    cassandra:
      keyspace-name: sgp_tx
      contactPoints: 127.0.0.1
      port: 9042